# Generated by Django 3.0.3 on 2021-03-13 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(null=True, upload_to='teacher_pictures')),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text='Required. 10 digits only. E.g 0552233444', max_length=10, null=True)),
                ('room_number', models.IntegerField(help_text='Class room number', unique=True, validators=[django.core.validators.MaxLengthValidator(999), django.core.validators.MinLengthValidator(0)])),
                ('subjects', models.ManyToManyField(to='teacherdirectory.Subject')),
            ],
        ),
    ]
 
