# Generated by Django 3.0.3 on 2021-03-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherdirectory', '0002_auto_20200707_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
 
