# Generated by Django 3.0.3 on 2021-03-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherdirectory', '0003_auto_20200707_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='room_number',
            field=models.CharField(help_text='Class room number/letter combination like 4c', max_length=10),
        ),
    ]
 
