# Generated by Django 3.0.3 on 2020-07-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherdirectory', '0004_auto_20200707_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='subjects',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='subjects',
            field=models.CharField(default='maths', max_length=1000),
            preserve_default=False,
        ),
    ]
 
