# Generated by Django 3.0.3 on 2020-07-07 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherdirectory', '0005_auto_20200707_0811'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
 